name: run Instrument Tests
run-name: ${{ github.actor }} is running Instrument Tests

on:
  workflow_dispatch:
    inputs:
      useUrlTestData:
        description: Enable download testdata from url
        type: boolean
        required: false
      instrument_options:
        description: Input subset of tests for testing
        required: false
env:
    PATH_TEST_SUITE: app/src/androidTest/assets/testRun.json

permissions:
  contents: read
  actions: read
  checks: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: 34
            target: google_apis
            arch: x86_64
            profile: "Nexus 6"
    steps:

      # - name: Trigger clean-up data ui testing
      #   run: |
      #     curl -XPOST -u "khoanhuynh-evizi:${{secrets.WDIO_ACCESS_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/Record360/webdriver-io/dispatches --data '{"event_type": "cleanup_data", "client_payload": {"company": "101", "framework": "android"}}'
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.WDIO_ACCESS_TOKEN}}
          repository: ${{secrets.WDIO_REPOS}}
          ref: ${{ secrets.WDIO_BRANCH }}
          submodules: true

      - name: Download Test data from firebase
        if: "${{ inputs.useUrlTestData == true }}"
        run: |
          echo "${{ secrets.FIREBASE_SDK_KEY }}" > firebase/firebase-sdk-key.json
          cd firebase
          npm install
          node firebase.js
          cd ../

      - name: Load Google Services File
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Load Gradle Properties File
        env:
          DATA: ${{secrets.GRADLE_PROPERTIES}}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "$DATA" | base64 -d > ~/.gradle/gradle.properties

      - name: Set Up JDK Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Download schema from staging using task:downloadApolloSchema 
        run: ./gradlew Submodule:sdk:downloadApolloSchema --endpoint=${{secrets.WDIO_ENDPOINT}} --schema=${{secrets.WDIO_PATH_SCHEMA}}

      - name: Build App
        run: ./gradlew assembleStagingDebugAndroidTest
        
      - name: Enable KVM for linux runners
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-cached-${{ matrix.version }}-${{ matrix.arch }}
          
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.version }}
          target: ${{ matrix.target }}
          profile: ${{ matrix.profile }}
          arch: ${{ matrix.arch }}
          avd-name: Nexus6_${{ matrix.version }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
          
      - name: Execute Staging Instrument on API ${{ matrix.version }}
        if: "${{ inputs.instrument_options == '' }}"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.version }}
          target: ${{ matrix.target }}
          profile: ${{ matrix.profile }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          avd-name: Nexus6_${{ matrix.version }}
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb shell wm size
            adb shell wm density
            chmod +x ./scripts/run-testsuite.sh
            ./scripts/run-testsuite.sh --package=com.record360.app.test.tests --path="$PATH_TEST_SUITE"
            
      - name: Execute custom instrument test ${{ inputs.instrument_options }} on API ${{ matrix.version }}
        if: "${{ inputs.instrument_options != '' }}"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.version }}
          target: ${{ matrix.target }}
          profile: ${{ matrix.profile }}
          arch: ${{ matrix.arch }}
          avd-name: Nexus6_${{ matrix.version }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb shell wm size
            adb shell wm density
            chmod +x ./scripts/run-tests.sh
            ./scripts/run-tests.sh --instrument-options=${{ inputs.instrument_options }}
            
      - name: Upload reports on API ${{ matrix.version }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-suite-${{ matrix.version }}
          path: |
            app/build/outputs/*/connected/*
            app/build/reports/androidTests/connected/**
      - name: Generate reports on API ${{ matrix.version }}
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Report Testsuite on API ${{ matrix.version }}
          path: app/build/outputs/*/connected/**/flavors/**/*.xml
          reporter: java-junit
          fail-on-empty: 'false'
          fail-on-error: 'false'
