name: iOS UI Test
run-name: ${{ github.actor }} is XCUITests
on:
  workflow_dispatch:    
    inputs:
      runner_type:
        description: 'Select the type of runner'
        required: true
        default: 'macos-latest'
        type: choice
        options:
          - macos-latest
          - macos-13
      useUrlTestData:
        description: Enable download testdata from url
        type: boolean
        required: false
      list_tests:
        description: Input subset of tests for testing
        required: false
      ios-version:
        description: 'iOS Version (e.g., 17.5)'
        required: false
        default: '17.5'
        type: string
env:
    PATH_TEST_SUITE: record360UITests/Resources/testRun.json

permissions:
  contents: read
  actions: read
  checks: write
  
jobs:
  build:
    name: Test UI on Simulator
    runs-on: ${{ github.event.inputs.runner_type }}
    # needs: clean-up-mobile-data-ui-testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.WDIO_ACCESS_TOKEN}}
          repository: ${{secrets.WDIO_IOS_REPOS}}
          ref: auto_latest # ${{ secrets.WDIO_IOS_BRANCH }}

      - name: Set up SSH Agent and Key
        uses: tanmancan/action-setup-ssh-agent-key@1.0.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          ssh-public-key: ${{ secrets.PUBLIC_KEY_CHECKOUT }}

      - name: Download Test data from firebase
        if: "${{ inputs.useUrlTestData == true }}"
        run: |
          echo "${{ secrets.FIREBASE_SDK_KEY }}" > record360UITests/Firebase/firebase-sdk-key.json
          cd record360UITests/Firebase
          npm install
          node firebase.js
          cd ../../
          
      - name: Install CocoaPods dependencies
        run: |
          pod install --repo-update
          pod update Record360SDK
        shell: bash
        
      - name: Copy Configuration plist
        run: sh ci_scripts/ci_configuration.sh
        shell: bash

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Install xcpretty from https://github.com/xcpretty
        run: |
          # Create temporary Gemfile just for xcpretty
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'xcpretty', git: 'https://github.com/xcpretty/xcpretty.git', branch: 'master'" >> Gemfile
          
          # Install using bundler
          bundle install
          
          # Verify version
          bundle exec xcpretty --version

      - name: Execute Staging-UI on iPhone 15
        env:
          IOS_VERSION: ${{ inputs.ios-version || '17.5' }}
        if: "${{ inputs.list_tests == '' }}"
        run: |
          chmod +x ./ci_scripts/run-testsuite.sh
          ./ci_scripts/run-testsuite.sh --testBundle=record360UITests --path="$PATH_TEST_SUITE" --iOSVersion="${IOS_VERSION}"
        shell: bash

      - name: Execute custom test Staging-UI on iPhone 15
        env:
          IOS_VERSION: ${{ inputs.ios-version || '17.5' }}
        if: "${{ inputs.list_tests != '' }}"
        run: |
          chmod +x ./ci_scripts/run-tests.sh
          ./ci_scripts/run-tests.sh --testBundle=record360UITests --list-tests=${{ inputs.list_tests }} --iOSVersion="${IOS_VERSION}"
        shell: bash

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: UI Test Result
          path: TestResult.xcresult
          retention-days: 7
