name: iOS UI Test
run-name: ${{ github.actor }} is XCUITests
on:
  workflow_dispatch:    
    inputs:
      runner_type:
        description: 'Input name of runner'
        required: true
        default: 'macos-latest'
        type: string
      useUrlTestData:
        description: Enable download testdata from url
        type: boolean
        required: false
      list_tests:
        description: Input subset of tests for testing
        required: false
      ios-version:
        description: 'iOS Version (e.g., 18.2)'
        required: false
        default: '18.2'
        type: string
      simulator-name:
        description: 'Simulator Name'
        required: false
        default: 'iPhone 16'
        type: string
      xcode-version:
        description: 'Xcode version'
        required: false
        default: '16.2'
        type: string
      testing-branch:
        description: 'testing branch(e.g., master)'
        required: false
        type: string
env:
    PATH_TEST_SUITE: record360UITests/Resources/testRun.json

permissions:
  contents: read
  actions: read
  checks: write
  
jobs:
  build:
    name: Test UI on Simulator
    runs-on: ${{ github.event.inputs.runner_type }}
    # needs: clean-up-mobile-data-ui-testing
    steps:    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.WDIO_ACCESS_TOKEN}}
          repository: ${{secrets.WDIO_IOS_REPOS}}
          ref: ${{ github.event.inputs.testing-branch || 'master' }}

      - name: Set up SSH Agent and Key
        uses: tanmancan/action-setup-ssh-agent-key@1.0.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          ssh-public-key: ${{ secrets.PUBLIC_KEY_CHECKOUT }}

      - name: Download Test data from firebase
        if: "${{ inputs.useUrlTestData == true }}"
        run: |
          echo "${{ secrets.FIREBASE_SDK_KEY }}" > record360UITests/Firebase/firebase-sdk-key.json
          cd record360UITests/Firebase
          npm install
          node firebase.js
          cd ../../
          
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ inputs.xcode-version || '16.2' }}
        
      - name: Install CocoaPods dependencies
        run: |
          pod install --repo-update
          pod update Record360SDK
        shell: bash
        
      - name: Copy Configuration plist
        run: sh ci_scripts/ci_configuration.sh
        shell: bash

      - name: Install xcpretty from https://github.com/xcpretty
        run: |
          # Create temporary Gemfile just for xcpretty
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'xcpretty', git: 'https://github.com/xcpretty/xcpretty.git', branch: 'master'" >> Gemfile
          
          # Install using bundler
          bundle install
          
          # Verify version
          bundle exec xcpretty --version
      
      - name: Set simulator environment
        run: |
          echo "SIMULATOR_NAME=${{ inputs.simulator-name || 'iPhone 17' }}" >> $GITHUB_ENV
        shell: bash
        
      - name: Boot and launch simulator
        env:
          IOS_VERSION: ${{ inputs.ios-version || '17.5' }}
        run: |
          # Update device type identifier for the given simulator name
          DEVICE_TYPE=$(xcrun simctl list devicetypes | awk -v name="${SIMULATOR_NAME}" -F'[()]' '$1 ~ name {gsub(/^ *| *$/,"",$1); if ($1==name) {print $2; exit}}')
          if [ -z "$DEVICE_TYPE" ]; then
            # Fallback to case-insensitive partial match
            DEVICE_TYPE=$(xcrun simctl list devicetypes | awk -v name="${SIMULATOR_NAME}" -F'[()]' 'tolower($1) ~ tolower(name) {print $2; exit}')
          fi
          if [ -z "$DEVICE_TYPE" ]; then
            echo "Failed to find device type for simulator name '${SIMULATOR_NAME}'"
            xcrun simctl list devicetypes
            exit 1
          fi

          VERSION_TYPE=$(xcrun simctl list runtimes | grep -i "iOS" | grep -i "${IOS_VERSION}" | awk '{print $NF}')

          # Create and boot simulator with the specific iOS version
          DEVICE_ID=$(xcrun simctl create "${SIMULATOR_NAME}" "${DEVICE_TYPE}" "${VERSION_TYPE}")
          echo "Created simulator with ID: $DEVICE_ID"
          xcrun simctl boot "$DEVICE_ID"
          
          # Wait for simulator to be fully booted
          xcrun simctl bootstatus "$DEVICE_ID" -b
          echo "Simulator booted successfully"
          
          # Prepare simulator for notifications
          # Enable notifications in system settings
          xcrun simctl spawn "$DEVICE_ID" defaults write com.apple.notificationcenterui NotificationWillShowInLockScreen -bool true
          xcrun simctl spawn "$DEVICE_ID" defaults write com.apple.notificationcenterui NotificationCenterEnabled -bool true
          xcrun simctl spawn "$DEVICE_ID" defaults write com.apple.springboard SBRingerMuted -bool false
          # Configure notification settings for the simulator
          xcrun simctl spawn "$DEVICE_ID" defaults write com.apple.Preferences AutoAcceptAlerts -bool true
          
          # Restart SpringBoard to apply settings
          xcrun simctl spawn "$DEVICE_ID" launchctl kickstart -k user/foreground/com.apple.SpringBoard
          xcrun simctl spawn "$DEVICE_ID" defaults read com.apple.springboard
          sleep 15
          echo "SpringBoard restarted"
          
          # Store simulator ID in github env
          echo "SIMULATOR_ID=$DEVICE_ID" >> $GITHUB_ENV
        
      - name: Execute Staging-UI
        if: "${{ inputs.list_tests == '' }}"
        run: |
          chmod +x ./ci_scripts/run-testsuite.sh
          ./ci_scripts/run-testsuite.sh --testBundle=record360UITests --path="$PATH_TEST_SUITE" --deviceName="${SIMULATOR_NAME}"
        shell: bash

      - name: Execute custom test Staging-UI
        if: "${{ inputs.list_tests != '' }}"
        run: |
          chmod +x ./ci_scripts/run-tests.sh
          ./ci_scripts/run-tests.sh --testBundle=record360UITests --list-tests=${{ inputs.list_tests }} --deviceName="${SIMULATOR_NAME}"
        shell: bash          

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: UI Test Result
          path: TestResult.xcresult
          retention-days: 7
